version = 3.10.7
runner.dialect = scala3

maxColumn = 80
indent.main = 2
indent.extendSite = 2
indent.defnSite = 2
indent.withSiteRelativeToExtends = 2

assumeStandardLibraryStripMargin = true
align.stripMargin = true
align.preset = some

rewrite.trailingCommas.style = "always"
rewrite.rules = [RedundantParens, SortModifiers]
rewrite.redundantParens.infixSide = some

newlines.source = keep
# verticalMultiline.atDefnSite = true
# verticalMultiline.arityThreshold = 2
verticalMultiline.newlineAfterOpenParen = true

newlines.topLevelStatementBlankLines = [
    { blanks { before = 1, after = 1, beforeEndMarker = 0 } }
]
newlines.beforeCurlyLambdaParams = always
newlines.afterCurlyLambdaParams = squash
newlines.implicitParamListModifierForce = [before, after]

binPack.parentConstructors = Always

danglingParentheses.defnSite = true
danglingParentheses.exclude = []
danglingParentheses.callSite = true
danglingParentheses.ctrlSite = false
